import groovy.json.JsonSlurper
import groovy.xml.XmlSlurper

plugins {
	id 'net.fabricmc.fabric-loom' // version from latest-loom.gradle via settings.gradle's pluginManagement
	id 'maven-publish'
}

def mc_version_name(){
	String key = 'minecraft_version_name'
	if (project.hasProperty(key)) {String value = project.getProperties().get(key); return !value.isEmpty() ? value : project.minecraft_version}
	else {return project.minecraft_version}
}
version = "${mod_version}+${mc_version_name()}-Fabric"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'ParchmentMC'
		url = 'https://maven.parchmentmc.org'
	}
	maven {
		name = 'Modrinth'
		url = 'https://api.modrinth.com/maven'
	}
}

loom {
}

fabricApi {
}

def getReleaseVersion(minecraftVersion) {
	// Truncate version after first non-integer/dot
	def releaseVersion = minecraftVersion.replaceAll(/[^0-9.].*/, '')
	if (minecraftVersion != releaseVersion) {println('==='); println('Resolved \"' + minecraftVersion + '\" as \"' + releaseVersion + '\" for Fabric and Parchment.');
		println('===')}
	return releaseVersion
}

def releaseVersion = getReleaseVersion(minecraft_version)

def getLatestFabric(minecraftVersion) {
	def fApiXmlUrl = 'https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/maven-metadata.xml'
	def fLoaderJsonUrl = 'https://meta.fabricmc.net/v2/versions/loader'

	def fLoaderJson = new JsonSlurper().parseText(new URI(fLoaderJsonUrl).toURL().text)
	def fLoaderLatestVersion = fLoaderJson.get(0).version
	println('Fabric Loader: ' + fLoaderLatestVersion)

	def fApiLatestVersion
	try {
		def metadata = new XmlSlurper().parse(fApiXmlUrl)
		def versions = metadata.versioning.versions.version*.text()
		fApiLatestVersion = versions.findAll { it ==~ /\d+(\.\d+)*.${minecraftVersion}/ }.last()
		println('Fabric Api: ' + fApiLatestVersion)
	} catch (Exception e) {
		throw new GradleException("Failed to fetch $fApiXmlUrl: ${e.message}")
	}
	return [fLoaderLatestVersion, fApiLatestVersion]
}

def (fabric_loader_version, fabric_api_version) = getLatestFabric(releaseVersion)

dependencies {
	implementation 'org.apache.commons:commons-text:1.12.0'
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

	// MStV
	localRuntime "maven.modrinth:more-stick-variants:${mstv_version_id}"
}

static def version_reduced(String input) { // Reduces a version string by one minor version and sets patch to 0
	def parts = input.split('\\.')
	if (parts.length < 2) throw new IllegalArgumentException("Invalid version: $input")
	def major = parts[0] as Integer
	def minor = (parts[1] as Integer) - 1
	return "${major}.${minor}.0"
}

def minecraft_version_0() {
	String key = 'minecraft_version_lower'
	if (project.hasProperty(key)) {String value = project.getProperties().get(key); return !value.isEmpty() ? value :
			version_reduced("${project.minecraft_version}") }
	else {return version_reduced("${project.minecraft_version}")} // Default to one minor version lower with patch = 0 as lower bound if none is specified
}

def minecraft_version_1() {
	String key = 'minecraft_version_upper'
	if (project.hasProperty(key)) {String value = project.getProperties().get(key); return !value.isEmpty() ? value : "99.0.0"}
	else {return "99.0.0"} // Effectively no upper bound
}

def getJavaVersionNum() { if (project.minecraft_version.startsWith("1.20")) return 17 else if (project.minecraft_version.startsWith("1.21")) return 21 else return 25 }
var java_version = getJavaVersionNum()
def getJavaVersionEnum() { if (project.minecraft_version.startsWith("1.20")) return JavaVersion.VERSION_17 else if (project.minecraft_version.startsWith("1.21")) return JavaVersion.VERSION_21 else return JavaVersion.VERSION_25 }
var java_version_enum = getJavaVersionEnum()

processResources {
	var fabric_loader_version_0 = version_reduced(fabric_loader_version)

	var replaceProperties = [
			loader_version: fabric_loader_version_0, mod_id: mod_id, mod_name: mod_name, mstv_version: mstv_version,
			mod_license: mod_license, mod_version: mod_version, mod_description: mod_description,
			minecraft_version: minecraft_version, minecraft_version_0: minecraft_version_0(), minecraft_version_1: minecraft_version_1(),
			java_version: java_version
	]
	inputs.properties replaceProperties

	filesMatching("fabric.mod.json") {
		expand replaceProperties
	}
	filesMatching("*.mixins.json") {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version
}

java {
	sourceCompatibility = java_version_enum
	targetCompatibility = java_version_enum
}

jar {
	from("LICENSE") {
		rename { "${project.base.archivesName.get()}_${it}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}