# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.11-pre2
minecraft_version_ranges = [1.21.4,1.21.11]
minecraft_version_lower = 1.21.1
minecraft_version_upper =

# File Name
minecraft_version_name = 1.21.4(-11)
archives_base_name = NemosMoreLadderVariants

# Mod Properties
mod_id = nemos-moreladdervariants
mod_name = Nemoʼs More Ladder Variants (MStV+)
mod_name_short = Nemoʼs More Ladder Variants
mod_description = This mod adds the variants of the Ladder item from the mod <Nemoʼs Carpentry> as a standalone mod.
mod_version = 1.0.10
mod_license = MIT
maven_group = de.pnku

# Dependencies
mstv_version = 1.4.11
mstv_version_id = yKwoTaT7