# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.1
minecraft_version_supported = [1.21,1.21.1]
minecraft_version_lower = 1.20.6
minecraft_version_upper = 1.21.4

# File Name
minecraft_version_name = 1.21(.1)
archives_base_name = NemosMoreLadderVariants

# Mod Properties
mod_id = nemos-moreladdervariants
mod_name = Nemo's More Ladder Variants (MStV+)
mod_name_short = Nemo's More Ladder Variants
mod_description = Adding variants of the Ladder Block/Item from the mod <Nemo's Carpentry> as a standalone mod
mod_version = 1.0.11
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
mstv_version = 1.4.14
mstv_version_id = 85QRWX5d