name: publish

on:
  push:
    paths:
      - 'CHANGELOG.md'
    branches:
      - '**'  # Allow all branches
    tags-ignore:
      - '*'   # Ignore all tag pushes

jobs:
  build:
    uses: pnk2u/.github/.github/workflows/publish.yml@main
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}